// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_SUBTASK_LIST = "GET_SUBTASK_LIST";

/**
* Add SUBTASK
*/
export const ADD_NEW_SUBTASK = "ADD_NEW_SUBTASK";
export const ADD_SUBTASK_SUCCESS = "ADD_SUBTASK_SUCCESS";
export const ADD_SUBTASK_FAIL = "ADD_SUBTASK_FAIL";

/**
 * Edit SUBTASK
 */
export const UPDATE_SUBTASK = "UPDATE_SUBTASK";
export const UPDATE_SUBTASK_SUCCESS = "UPDATE_SUBTASK_SUCCESS";
export const UPDATE_SUBTASK_FAIL = "UPDATE_SUBTASK_FAIL";

/**
 * Delete SUBTASK
 */
export const DELETE_SUBTASK = "DELETE_SUBTASK";
export const DELETE_SUBTASK_SUCCESS = "DELETE_SUBTASK_SUCCESS";
export const DELETE_SUBTASK_FAIL = "DELETE_SUBTASK_FAIL";