// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_SPRINT_LIST = "GET_SPRINT_LIST";

export const GET_SPRINT_LIST_ON_GLOBAL_SEARCH = "GET_SPRINT_LIST_ON_GLOBAL_SEARCH";


/**
 * Edit SPRINT
 */
export const GET_SPRINT_DETAIL = "GET_SPRINT_DETAIL";
export const GET_SPRINT_DETAIL_SUCCESS = "GET_SPRINT_DETAIL_SUCCESS";
export const GET_SPRINT_DETAIL_FAIL = "GET_SPRINT_DETAIL_FAIL";


/**
* Add SPRINT
*/
export const ADD_NEW_SPRINT = "ADD_NEW_SPRINT";
export const ADD_SPRINT_SUCCESS = "ADD_SPRINT_SUCCESS";
export const ADD_SPRINT_FAIL = "ADD_SPRINT_FAIL";

/**
 * Edit SPRINT
 */
export const UPDATE_SPRINT = "UPDATE_SPRINT";
export const UPDATE_SPRINT_SUCCESS = "UPDATE_SPRINT_SUCCESS";
export const UPDATE_SPRINT_FAIL = "UPDATE_SPRINT_FAIL";

/**
 * Delete SPRINT
 */
export const DELETE_SPRINT = "DELETE_SPRINT";
export const DELETE_SPRINT_SUCCESS = "DELETE_SPRINT_SUCCESS";
export const DELETE_SPRINT_FAIL = "DELETE_SPRINT_FAIL";