// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_LABEL_LIST_BY_TASK = "GET_LABEL_LIST_BY_TASK";
export const GET_LABEL_LIST_BY_TASK_FOR_DETAILS = "GET_LABEL_LIST_BY_TASK_FOR_DETAILS";
export const GET_ALL_LABEL = "GET_ALL_LABEL";

/**
* Add LABEL
*/
export const ADD_NEW_LABEL = "ADD_NEW_LABEL";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS";
export const ADD_LABEL_FAIL = "ADD_LABEL_FAIL";

/**
 * Edit LABEL
 */
export const UPDATE_LABEL = "UPDATE_LABEL";
export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS";
export const UPDATE_LABEL_FAIL = "UPDATE_LABEL_FAIL";

/**
 * Delete LABEL
 */
export const DELETE_LABEL = "DELETE_LABEL";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";
export const DELETE_LABEL_FAIL = "DELETE_LABEL_FAIL";