// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_BACKLOG_LIST = "GET_BACKLOG_LIST";

/**
* Add BACKLOG
*/
export const ADD_NEW_BACKLOG = "ADD_NEW_BACKLOG";
export const ADD_BACKLOG_SUCCESS = "ADD_BACKLOG_SUCCESS";
export const ADD_BACKLOG_FAIL = "ADD_BACKLOG_FAIL";

/**
 * Edit BACKLOG
 */
export const UPDATE_BACKLOG = "UPDATE_BACKLOG";
export const UPDATE_BACKLOG_SUCCESS = "UPDATE_BACKLOG_SUCCESS";
export const UPDATE_BACKLOG_FAIL = "UPDATE_BACKLOG_FAIL";

/**
 * Delete BACKLOG
 */
export const DELETE_BACKLOG = "DELETE_BACKLOG";
export const DELETE_BACKLOG_SUCCESS = "DELETE_BACKLOG_SUCCESS";
export const DELETE_BACKLOG_FAIL = "DELETE_BACKLOG_FAIL";